-- Add sequential customer_id to profiles
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Make it unique and indexed for fast lookup
CREATE UNIQUE INDEX IF NOT EXISTS profiles_customer_id_idx ON profiles(customer_id);

-- Explicit comment for documentation
COMMENT ON COLUMN profiles.customer_id IS 'Unique sequential numeric ID for easy customer identification in POS (1, 2, 3...)';
