-- Add order_number column
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Optional: If you want to start from specific number
-- ALTER TABLE orders ALTER COLUMN order_number RESTART WITH 1000;

-- Index for searching by number
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);

COMMENT ON COLUMN orders.order_number IS 'Human friendly sequential order number';
