-- Drop the existing foreign key constraint on cash_movements related_order_id
-- We assume the default name or name generated by PG. We'll try to drop by finding it or using common name.

DO $$
DECLARE
    constraint_record RECORD;
BEGIN
    FOR constraint_record IN 
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'cash_movements' 
        AND constraint_type = 'FOREIGN KEY'
    LOOP
        -- Check if this FK points to orders
        IF EXISTS (
            SELECT 1 FROM information_schema.key_column_usage kcu
            JOIN information_schema.constraint_column_usage ccu ON kcu.constraint_name = ccu.constraint_name
            WHERE kcu.constraint_name = constraint_record.constraint_name
            AND kcu.table_name = 'cash_movements'
            AND kcu.column_name = 'related_order_id'
            AND ccu.table_name = 'orders'
        ) THEN
            EXECUTE 'ALTER TABLE cash_movements DROP CONSTRAINT ' || quote_ident(constraint_record.constraint_name);
        END IF;
    END LOOP;
END $$;

-- Re-add the constraint with ON DELETE CASCADE
ALTER TABLE cash_movements
ADD CONSTRAINT cash_movements_related_order_id_fkey
FOREIGN KEY (related_order_id)
REFERENCES orders(id)
ON DELETE CASCADE;
