-- 1. Create Tax Conditions Catalog
create table if not exists tax_conditions (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. 'Responsable Inscripto', 'Monotributista'
  code text not null unique, -- AFIP code or internal code
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed Tax Conditions
insert into tax_conditions (name, code) values
('IVA Responsable Inscripto', 'RI'),
('IVA Responsable No Inscripto', 'RNI'),
('IVA No Responsable', 'NR'),
('IVA Sujeto Exento', 'EX'),
('Consumidor Final', 'CF'),
('Responsable Monotributo', 'RM'),
('Sujeto No Categorizado', 'SNC'),
('Proveedor del Exterior', 'PE'),
('Cliente del Exterior', 'CE'),
('IVA Liberado - Ley Nº 19.640', 'IBL'),
('IVA Responsable Inscripto – Agente de Percepción', 'RIAP'),
('Pequeño Contribuyente Eventual', 'PCE'),
('Monotributista Social', 'MS'),
('Pequeño Contribuyente Eventual Social', 'PCES')
on conflict (code) do nothing;

-- 2. Extend Profiles Table with Fiscal Data
alter table profiles add column if not exists cuit text unique;
alter table profiles add column if not exists business_name text; -- Razón Social
alter table profiles add column if not exists tax_condition_id bigint references tax_conditions(id);
alter table profiles add column if not exists fiscal_address text;

-- 3. Create Invoices Table
create table if not exists invoices (
  id uuid default gen_random_uuid() primary key,
  order_id text references orders(id), -- Nullable in case we invoice something else later
  profile_id uuid references profiles(id), -- Client
  
  -- AFIP Data
  cae text,
  cae_expiration date,
  invoice_type text not null, -- 'A', 'B', 'C'
  sale_point int not null,
  invoice_number bigint not null,
  
  -- Amounts
  total_amount numeric(10, 2) not null,
  net_amount numeric(10, 2) not null,
  vat_amount numeric(10, 2) default 0,
  
  -- Status
  status text default 'pending', -- 'pending', 'authorized', 'rejected'
  afip_response jsonb, -- Store full response for debugging
  afip_error text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Invoices
alter table invoices enable row level security;

create policy "Admins can view all invoices" on invoices
  for select using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Users can view their own invoices" on invoices
  for select using (
    auth.uid() = profile_id
  );

-- Allow admins to insert/update invoices (system level usually)
create policy "Admins can manage invoices" on invoices
  for all using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Indexes for performance
create index if not exists idx_invoices_order_id on invoices(order_id);
create index if not exists idx_invoices_profile_id on invoices(profile_id);
create index if not exists idx_profiles_cuit on profiles(cuit);
