export const countryCodes = [
    { code: "+54", country: "Argentina", flag: "🇦🇷" },
    { code: "+1", country: "United States", flag: "🇺🇸" },
    { code: "+55", country: "Brazil", flag: "🇧🇷" },
    { code: "+56", country: "Chile", flag: "🇨🇱" },
    { code: "+598", country: "Uruguay", flag: "🇺🇾" },
    { code: "+595", country: "Paraguay", flag: "🇵🇾" },
    { code: "+591", country: "Bolivia", flag: "🇧🇴" },
    { code: "+51", country: "Peru", flag: "🇵🇪" },
    { code: "+57", country: "Colombia", flag: "🇨🇴" },
    { code: "+58", country: "Venezuela", flag: "🇻🇪" },
    { code: "+593", country: "Ecuador", flag: "🇪🇨" },
    { code: "+52", country: "Mexico", flag: "🇲🇽" },
    { code: "+34", country: "Spain", flag: "🇪🇸" },
    { code: "+33", country: "France", flag: "🇫🇷" },
    { code: "+39", country: "Italy", flag: "🇮🇹" },
    { code: "+49", country: "Germany", flag: "🇩🇪" },
    { code: "+44", country: "United Kingdom", flag: "🇬🇧" },
    { code: "+86", country: "China", flag: "🇨🇳" },
    { code: "+81", country: "Japan", flag: "🇯🇵" },
    { code: "+91", country: "India", flag: "🇮🇳" },
    // Add more as needed or use a full library if requested, but this covers main ones + region
].sort((a, b) => a.country.localeCompare(b.country))
